language: java

jdk:
  - openjdk8 

cache:
  directories:
    - "$HOME/.cache"
jobs:
    - stage:deploy
      name:"deploy to dev environment"
      script: 
        - mvn clean install 
        - cp .travis.settings.xml $HOME/.m2/.settings.xml
        - mvn deploy -DmuleDeploy -Dserver=$server  -Dworkers=$workers -DworkerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion -Dapplication.name=$application.name
      if: branch=master  
